version: "3.9"

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    depends_on:
      - backend
    command: [ "bun", "run", "dev" ]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
