version: "3.9"

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./app:/app
    depends_on:
      - backend
    command: ["bun", "run", "dev"]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    command: ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]
